# Generated by Django 4.1.6 on 2023-02-06 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0002_alter_pullrequest_status'),
        ('helpdesk', '0002_alter_field_branch_alter_field_original_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='child_nodes',
        ),
        migrations.RemoveField(
            model_name='node',
            name='child_fields',
        ),
        migrations.AddField(
            model_name='field',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='helpdesk.node'),
        ),
        migrations.AddField(
            model_name='node',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='helpdesk.field'),
        ),
        migrations.AlterField(
            model_name='field',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='vcs.branch'),
        ),
        migrations.AlterField(
            model_name='node',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='vcs.branch'),
        ),
    ]
