# Generated by Django 4.1.6 on 2023-02-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_remove_field_child_nodes_remove_node_child_fields_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='help_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='initial',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='field',
            name='label',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='placeholder',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[('select', 'Select'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'Datetime'), ('image', 'Image'), ('file', 'File')], max_length=10),
        ),
    ]
