# Generated by Django 4.1.6 on 2023-02-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0004_alter_field_help_text_alter_field_initial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='label',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='field',
            name='placeholder',
            field=models.CharField(blank=True, default='Обери із списку', max_length=64),
        ),
    ]
