# Generated by Django 3.0.10 on 2023-02-16 15:02

import django.contrib.sessions.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('middle_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('condition', models.CharField(max_length=64)),
                ('departament', models.CharField(max_length=255)),
                ('depcode', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('gmail', models.CharField(max_length=64)),
                ('hired_date', models.DateField(blank=True, null=True)),
                ('int_phone', models.CharField(max_length=32)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('poscode', models.CharField(max_length=64)),
                ('position', models.CharField(max_length=128)),
                ('refresh_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('management_level', models.IntegerField()),
                ('room_number', models.CharField(max_length=64)),
                ('staff_type_processed', models.BooleanField()),
                ('inn', models.CharField(max_length=32)),
                ('glob_id', models.CharField(max_length=24)),
                ('is_head', models.BooleanField()),
                ('photo', models.CharField(blank=True, max_length=100, null=True)),
                ('dt_create', models.DateTimeField(blank=True, null=True)),
                ('dir_depcode', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'users_employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sessions.Session')),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
            bases=('sessions.session',),
            managers=[
                ('objects', django.contrib.sessions.models.SessionManager()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('tin', models.CharField(blank=True, max_length=10, null=True)),
                ('ref_id', models.IntegerField(blank=True, null=True)),
                ('has_overdue', models.BooleanField()),
                ('glob_id', models.CharField(blank=True, max_length=24, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=128, null=True)),
                ('is_head', models.BooleanField()),
                ('dt_set_overdue', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users_user',
                'managed': False,
            },
        ),
    ]
