# Generated by Django 4.1.6 on 2023-02-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'Merged'), (3, 'Closed'), (4, 'Conflict'), (5, 'Returned')], default=1),
        ),
    ]
